---
title: block
---
block-beta
    columns 4
    a["a"]
    b:3
    c:2
    d:2
    block:group1:4
        e("e")
        f{"f"}
        space:2
        g(("g"))
        h{{"h"}}
    end
    block:group2:4
        i
        space
        j
        space
        k

        i -- "text" --> j
        k -- "text" --> j
    end

