---
title: gantt
---
gantt
    dateFormat  YYYYMMDD
    section section1
    task1: done, t1, 20200101, 14d
    task2: crit, after t1, 30d
    task3: 20200201, 90d
    
    section section2
    task4: active, 20200101, 26w
    task5: milestone, 20200121