---
title: mindmap
---
mindmap
  root("root")
    branch1
      leaf1(("text"))
      branch1a
        leaf2("text")
    branch2
      leaf2
      ::icon(fa fa-leaf)
      branch2a
        branch2b
            leaf2b1))"text"((
            leaf2b2)"text"(
            leaf2b3{{"text"}}