---
title: quadrant
---
quadrantChart
    x-axis lowx --> highx
    y-axis lowy --> highy
    quadrant-1 highxhighy
    quadrant-2 lowxhighy
    quadrant-3 lowxlowy
    quadrant-4 highxlowy
    A: [0.9, 0.1]
    B: [0.5, 0.5]
    C: [0.2, 0.8]
