---
title: sankey
---
sankey-beta
%% source,target,value
Source1, Target1, 100
Source1, Target2, 50.68
Source1, Midpoint1, 20

Source2, Midpoint1, 20
Source2, Midpoint2, 20

Midpoint1, Target1, 10
Midpoint1, Target3, 30

Midpoint2, Target2, 10
Midpoint2, Target3, 10