---
title: sequence
---
sequenceDiagram
    participant a as participanta
    participant b as participantb
    participant c as participantc
    note left of a: text
    note over b: text
    a ->> b: message to b
    a ->> b: message to a
    c -->> a: test
